AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation template provisions the resources required for react-map-with-markers.

Parameters:
  # Allow one of the Amazon Location map styles to be selected from a list
  MapStyle:
    Type: String
    Default: VectorEsriTopographic
    AllowedValues:
      - VectorEsriTopographic
      - VectorEsriStreets
      - VectorEsriNavigation
      - VectorEsriLightGrayCanvas
      - VectorEsriDarkGrayCanvas
      - RasterEsriImagery
      - VectorGrabStandardLight
      - VectorGrabStandardDark
      - VectorHereExplore
      - VectorHereExploreTruck
      - RasterHereExploreSatellite
      - HybridHereExploreSatellite
      - VectorHereContrast
      - VectorOpenDataStandardLight
      - VectorOpenDataStandardDark
      - VectorOpenDataVisualizationLight
      - VectorOpenDataVisualizationDark
    Description: Amazon Location map style. Grab styles are only available in the Asia Pacific (Singapore) Region (ap-southeast-1)

Resources:
  # Create a Cognito Identity pool that supports unauthenticated (anonymous) users
  CognitoIdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      AllowUnauthenticatedIdentities: true
      IdentityPoolName: react-map-with-markers

  # Create an IAM role with permission to call Amazon Location Maps that will be mapped to
  # unauthenticated requests by the Cognito Identity Pool
  CognitoIdentityPoolUnauthRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
            Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: react-map-with-markers-unauth-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "geo:GetMap*"
                Resource: !GetAtt AmazonLocationMap.Arn

  # Attach the IAM role to the Identity Pool
  CognitoIdentityPoolDefaultRoleAttachment:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        unauthenticated: !GetAtt CognitoIdentityPoolUnauthRole.Arn

  # Create an Amazon Location Map resource using the style passed in as a parameter
  AmazonLocationMap:
    Type: AWS::Location::Map
    Properties:
      Configuration:
        Style: !Ref MapStyle
      Description: !Sub "Managed by CloudFormation: ${AWS::StackName}"
      MapName: react-map-with-markers

# Outputs to transcribe into .env to configure the React app
Outputs:
  # Value to fill in as VITE_IDENTITY_POOL_ID
  IdentityPoolId:
    Value: !Ref CognitoIdentityPool

  # Value to fill in as VITE_REGION
  Region:
    Value: !Sub "${AWS::Region}"

  # Value to fill in as VITE_MAP_NAME
  MapName:
    Value: react-map-with-markers

  # Value to fill in as VITE_MAP_STYLE
  MapStyle:
    Value: !Ref MapStyle
