AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation template provisions the resources required for react-map-with-markers.

Resources:
  # Create an API key that has access to maps
  AmazonLocationApiKey:
    Type: AWS::Location::APIKey
    DeletionPolicy: Retain
    Properties:
      KeyName: react-map-with-markers
      Description: API Key for Amazon Location Service Maps
      NoExpiry: true
      Restrictions:
        AllowActions:
          - "geo-maps:*"
        AllowResources:
          - !Sub "arn:aws:geo-maps:${AWS::Region}::provider/default"

# Outputs to transcribe into .env to configure the React app
Outputs:
  # Value to fill in as VITE_API_KEY
  ApiKey:
    Value: !Ref AmazonLocationApiKey

  # Value to fill in as VITE_REGION
  Region:
    Value: !Sub ${AWS::Region}
